name: Docker Image CI

on:
  workflow_dispatch:

env:
  # Docker image name
  IMAGE_NAME: papilot

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
    
    - name: Log into registry
      run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u puqingee --password-stdin
    - name: Push image
      run: |
        IMAGE_ID=libra146/$IMAGE_NAME
        VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        # 设置镜像 id 和版本号
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        # 进行 push
        docker push $IMAGE_ID:$VERSION
